<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sysadm-PC" ignored="0" name="NB Air" tests="2" failures="1" timestamp="13 Mar 2019 11:26:08 GMT" time="640.792" errors="0">
  <testcase name="airDom_OW_GDS_NB_Retry_CCBooking_153" time="51.266" classname="testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking">
    <skipped/>
  </testcase> <!-- airDom_OW_GDS_NB_Retry_CCBooking_153 -->
  <testcase name="airDom_OW_GDS_NB_Retry_CCBooking_153" time="576.641" classname="testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking">
    <failure type="java.lang.AssertionError" message="Booking failed after 3 attempts">
      <![CDATA[java.lang.AssertionError: Booking failed after 3 attempts
	at testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking.airDom_OW_GDS_NB_Retry_CCBooking_153(AirDom_OW_GDS_NB_Retry_CCBooking.java:128)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- airDom_OW_GDS_NB_Retry_CCBooking_153 -->
</testsuite> <!-- NB Air -->
