<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="15" failed="15" ignored="0" total="35" passed="5">
  <reporter-output>
    <line>
      <![CDATA[url  /partners/account/forgotPassword]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/user/search]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/signin]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/signup]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/social/signup]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignupV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinusersearchV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinforgetpasswordV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinsigninV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinsocialsignupV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/user/search]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/signup]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/signin]]>
    </line>
    <line>
      <![CDATA[url  /partners/v2/social/signup]]>
    </line>
    <line>
      <![CDATA[url  /partners/account/forgotPassword]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignupV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinforgetpasswordV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinsocialsignupV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinusersearchV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinsigninV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/account/resetPassword]]>
    </line>
    <line>
      <![CDATA[url  /partners/signup]]>
    </line>
    <line>
      <![CDATA[url  /partners/signin]]>
    </line>
    <line>
      <![CDATA[url  /partners/user/search]]>
    </line>
    <line>
      <![CDATA[url  /partners/social/signup]]>
    </line>
    <line>
      <![CDATA[Response body flyinresetpasswordV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/account/resetPassword]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignup : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/signup]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignin : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/signin]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignup : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/social/signup]]>
    </line>
    <line>
      <![CDATA[Response body flyinusersearch : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /partners/user/search]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignup : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinresetpasswordV2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /account/partner/people/v1/traveller]]>
    </line>
    <line>
      <![CDATA[url  /account/partner/people/v1/search?emails=test@flyin.com&partner=1]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignup : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body flyinsignin : ]]>
    </line>
    <line>
      <![CDATA[Response body flyinusersearch : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /account/people?docRequired=false&email=kirti.pandey@cleartrip.com&partner=1&travellersRequired=false&userPreference=false]]>
    </line>
    <line>
      <![CDATA[url  account/people/7707500017642?docRequired=false&partner=1&travellersRequired=false&userPreference=false]]>
    </line>
    <line>
      <![CDATA[url  /people/traveller]]>
    </line>
    <line>
      <![CDATA[Response body partnercontroller_updatetraveller : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /account/partner/people/v1/traveller]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyemail : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /account/people?docRequired=false&email=kirti.pandey@cleartrip.com&partner=1&travellersRequired=false&userPreference=false]]>
    </line>
    <line>
      <![CDATA[url  /account/people/v2/41623980?docRequired=true&savedCards=true&travellersRequired=true&userPreference=true]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyid : ]]>
    </line>
    <line>
      <![CDATA[Response body travellercontroller_updatetraveller : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  account/people/7707500017642?docRequired=false&partner=1&travellersRequired=false&userPreference=false]]>
    </line>
    <line>
      <![CDATA[url  /people/traveller]]>
    </line>
    <line>
      <![CDATA[Response body partnercontroller_updatetraveller : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyemail : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /ctauth/client]]>
    </line>
    <line>
      <![CDATA[Response body travellercontroller_updatetraveller : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyid : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyid_v2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[url  /account/people/v2/41623980?docRequired=true&savedCards=true&travellersRequired=true&userPreference=true]]>
    </line>
    <line>
      <![CDATA[Response body null : {"message":"Given Client id doesn't Exist","traceId":"dba4cad1a88dda65"}]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body null : {"message":"Not authorized, Invalid token","traceId":"0af499968f397ea3"}]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body identityserviceaddclient : {"id":"5eafa4e577438f00088fafa0","clientId":"likhithaabeO","clientSecret":"{DAax3ctffbhWZtvOfYFeiH1CFW1ngBbzSypaS6omAHc=}b6e8a21ff70da6ad86b6ffac12de596d3ee79e97","authenticated":true,"scope":"all","authorizedGrantTypes":"read,write,trust","redirectUri":["http://localhost:8080/ctauth/authorize"],"authorities":"authorities","session":true,"append":false}]]>
    </line>
    <line>
      <![CDATA[statusCode: 200]]>
    </line>
    <line>
      <![CDATA[Response body null : {"message":"Given Client id doesn't Exist","traceId":"69262e5d6e83b544"}]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
    <line>
      <![CDATA[Response body peoplecontroller_getuserbyid_v2 : ]]>
    </line>
    <line>
      <![CDATA[statusCode: 401]]>
    </line>
  </reporter-output>
  <suite name="Accounts Service JAVA API - BB " duration-ms="6849" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:18Z">
    <groups>
    </groups>
    <test name="Account_Service_FlyinV2_SignUp" duration-ms="3421" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_FlyinV2_SignUP">
        <test-method status="SKIP" signature="flyinSignup()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_SignUP@7f552bd3]" name="flyinSignup" duration-ms="2948" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_SignUP.flyinSignup(Account_Service_FlyinV2_SignUP.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignupV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignup -->
        <test-method status="FAIL" signature="flyinSignup()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_SignUP@7f552bd3]" name="flyinSignup" duration-ms="424" started-at="2020-05-04T05:15:14Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_SignUP.flyinSignup(Account_Service_FlyinV2_SignUP.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignupV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignup -->
      </class> <!-- accountsAPI.Account_Service_FlyinV2_SignUP -->
    </test> <!-- Account_Service_FlyinV2_SignUp -->
    <test name="Account_Service_FlyinV2_Signin" duration-ms="3503" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_FlyinV2_Signin">
        <test-method status="SKIP" signature="flyinSignIn()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_Signin@12e61fe6]" name="flyinSignIn" duration-ms="2946" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_Signin.flyinSignIn(Account_Service_FlyinV2_Signin.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/signin]]>
            </line>
            <line>
              <![CDATA[Response body flyinsigninV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignIn -->
        <test-method status="FAIL" signature="flyinSignIn()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_Signin@12e61fe6]" name="flyinSignIn" duration-ms="467" started-at="2020-05-04T05:15:14Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_Signin.flyinSignIn(Account_Service_FlyinV2_Signin.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/signin]]>
            </line>
            <line>
              <![CDATA[Response body flyinsigninV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignIn -->
      </class> <!-- accountsAPI.Account_Service_FlyinV2_Signin -->
    </test> <!-- Account_Service_FlyinV2_Signin -->
    <test name="Account_Service_FlyinV2_Social_SignUp" duration-ms="3438" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_FlyinV2_SocialSignup">
        <test-method status="SKIP" signature="flyinV2socialsignup()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_SocialSignup@2f7c2f4f]" name="flyinV2socialsignup" duration-ms="2933" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_SocialSignup.flyinV2socialsignup(Account_Service_FlyinV2_SocialSignup.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/social/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsocialsignupV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinV2socialsignup -->
        <test-method status="FAIL" signature="flyinV2socialsignup()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_SocialSignup@2f7c2f4f]" name="flyinV2socialsignup" duration-ms="424" started-at="2020-05-04T05:15:14Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_SocialSignup.flyinV2socialsignup(Account_Service_FlyinV2_SocialSignup.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/social/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsocialsignupV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinV2socialsignup -->
      </class> <!-- accountsAPI.Account_Service_FlyinV2_SocialSignup -->
    </test> <!-- Account_Service_FlyinV2_Social_SignUp -->
    <test name="Account_Service_FlyinV2_UserSearch" duration-ms="3436" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_FlyinV2_UserSearch">
        <test-method status="SKIP" signature="flyinusersearchV2()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_UserSearch@10e92f8f]" name="flyinusersearchV2" duration-ms="2914" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_UserSearch.flyinusersearchV2(Account_Service_FlyinV2_UserSearch.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/user/search]]>
            </line>
            <line>
              <![CDATA[Response body flyinusersearchV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinusersearchV2 -->
        <test-method status="FAIL" signature="flyinusersearchV2()[pri:0, instance:accountsAPI.Account_Service_FlyinV2_UserSearch@10e92f8f]" name="flyinusersearchV2" duration-ms="446" started-at="2020-05-04T05:15:14Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_FlyinV2_UserSearch.flyinusersearchV2(Account_Service_FlyinV2_UserSearch.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/v2/user/search]]>
            </line>
            <line>
              <![CDATA[Response body flyinusersearchV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinusersearchV2 -->
      </class> <!-- accountsAPI.Account_Service_FlyinV2_UserSearch -->
    </test> <!-- Account_Service_FlyinV2_UserSearch -->
    <test name="Account_Service_Flyin_ForgotPassword" duration-ms="3400" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_Flyin_ForgotPassword">
        <test-method status="SKIP" signature="flyinforgetpasswordV2()[pri:0, instance:accountsAPI.Account_Service_Flyin_ForgotPassword@1d119efb]" name="flyinforgetpasswordV2" duration-ms="2939" started-at="2020-05-04T05:15:11Z" finished-at="2020-05-04T05:15:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_ForgotPassword.flyinforgetpasswordV2(Account_Service_Flyin_ForgotPassword.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/account/forgotPassword]]>
            </line>
            <line>
              <![CDATA[Response body flyinforgetpasswordV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinforgetpasswordV2 -->
        <test-method status="FAIL" signature="flyinforgetpasswordV2()[pri:0, instance:accountsAPI.Account_Service_Flyin_ForgotPassword@1d119efb]" name="flyinforgetpasswordV2" duration-ms="420" started-at="2020-05-04T05:15:14Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_ForgotPassword.flyinforgetpasswordV2(Account_Service_Flyin_ForgotPassword.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/account/forgotPassword]]>
            </line>
            <line>
              <![CDATA[Response body flyinforgetpasswordV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinforgetpasswordV2 -->
      </class> <!-- accountsAPI.Account_Service_Flyin_ForgotPassword -->
    </test> <!-- Account_Service_Flyin_ForgotPassword -->
    <test name="Account_Service_Flyin_SignUp" duration-ms="748" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_Flyin_Signup">
        <test-method status="SKIP" signature="signupV1()[pri:0, instance:accountsAPI.Account_Service_Flyin_Signup@703580bf]" name="signupV1" duration-ms="397" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Signup.signupV1(Account_Service_Flyin_Signup.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignup : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- signupV1 -->
        <test-method status="FAIL" signature="signupV1()[pri:0, instance:accountsAPI.Account_Service_Flyin_Signup@703580bf]" name="signupV1" duration-ms="336" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Signup.signupV1(Account_Service_Flyin_Signup.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignup : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- signupV1 -->
      </class> <!-- accountsAPI.Account_Service_Flyin_Signup -->
    </test> <!-- Account_Service_Flyin_SignUp -->
    <test name="Account_Service_Flyin_ResetPassword" duration-ms="785" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_Flyin_ResetPassword">
        <test-method status="SKIP" signature="flyinresetpasswordV2()[pri:0, instance:accountsAPI.Account_Service_Flyin_ResetPassword@5ae50ce6]" name="flyinresetpasswordV2" duration-ms="315" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_ResetPassword.flyinresetpasswordV2(Account_Service_Flyin_ResetPassword.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/account/resetPassword]]>
            </line>
            <line>
              <![CDATA[Response body flyinresetpasswordV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinresetpasswordV2 -->
        <test-method status="FAIL" signature="flyinresetpasswordV2()[pri:0, instance:accountsAPI.Account_Service_Flyin_ResetPassword@5ae50ce6]" name="flyinresetpasswordV2" duration-ms="446" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_ResetPassword.flyinresetpasswordV2(Account_Service_Flyin_ResetPassword.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/account/resetPassword]]>
            </line>
            <line>
              <![CDATA[Response body flyinresetpasswordV2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinresetpasswordV2 -->
      </class> <!-- accountsAPI.Account_Service_Flyin_ResetPassword -->
    </test> <!-- Account_Service_Flyin_ResetPassword -->
    <test name="Account_Service_Flyin_SocialSignUp" duration-ms="821" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_Flyin_Social_Signup">
        <test-method status="SKIP" signature="Flyinsocialsignup()[pri:0, instance:accountsAPI.Account_Service_Flyin_Social_Signup@29626d54]" name="Flyinsocialsignup" duration-ms="403" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Social_Signup.Flyinsocialsignup(Account_Service_Flyin_Social_Signup.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/social/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignup : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- Flyinsocialsignup -->
        <test-method status="FAIL" signature="Flyinsocialsignup()[pri:0, instance:accountsAPI.Account_Service_Flyin_Social_Signup@29626d54]" name="Flyinsocialsignup" duration-ms="369" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Social_Signup.Flyinsocialsignup(Account_Service_Flyin_Social_Signup.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/social/signup]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignup : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- Flyinsocialsignup -->
      </class> <!-- accountsAPI.Account_Service_Flyin_Social_Signup -->
    </test> <!-- Account_Service_Flyin_SocialSignUp -->
    <test name="Account_Service_Flyin_Signin" duration-ms="830" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_Flyin_Signin">
        <test-method status="SKIP" signature="flyinSignIn()[pri:0, instance:accountsAPI.Account_Service_Flyin_Signin@4a22f9e2]" name="flyinSignIn" duration-ms="394" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Signin.flyinSignIn(Account_Service_Flyin_Signin.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/signin]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignin : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignIn -->
        <test-method status="FAIL" signature="flyinSignIn()[pri:0, instance:accountsAPI.Account_Service_Flyin_Signin@4a22f9e2]" name="flyinSignIn" duration-ms="410" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Signin.flyinSignIn(Account_Service_Flyin_Signin.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/signin]]>
            </line>
            <line>
              <![CDATA[Response body flyinsignin : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinSignIn -->
      </class> <!-- accountsAPI.Account_Service_Flyin_Signin -->
    </test> <!-- Account_Service_Flyin_Signin -->
    <test name="Account_Service_Flyin_UserSearch" duration-ms="847" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
      <class name="accountsAPI.Account_Service_UserSearch">
        <test-method status="SKIP" signature="flyinusersearch()[pri:0, instance:accountsAPI.Account_Service_UserSearch@353d0772]" name="flyinusersearch" duration-ms="464" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_UserSearch.flyinusersearch(Account_Service_UserSearch.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/user/search]]>
            </line>
            <line>
              <![CDATA[Response body flyinusersearch : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinusersearch -->
        <test-method status="FAIL" signature="flyinusersearch()[pri:0, instance:accountsAPI.Account_Service_UserSearch@353d0772]" name="flyinusersearch" duration-ms="335" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_UserSearch.flyinusersearch(Account_Service_UserSearch.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /partners/user/search]]>
            </line>
            <line>
              <![CDATA[Response body flyinusersearch : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- flyinusersearch -->
      </class> <!-- accountsAPI.Account_Service_UserSearch -->
    </test> <!-- Account_Service_Flyin_UserSearch -->
    <test name="Account_Service_partnercontroller_Usersearch" duration-ms="382" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
      <class name="accountsAPI.Account_Service_Partnercontroller_Usersearch">
        <test-method status="PASS" signature="partnercontroller_usersearch()[pri:0, instance:accountsAPI.Account_Service_Partnercontroller_Usersearch@1700915]" name="partnercontroller_usersearch" duration-ms="380" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
          <reporter-output>
            <line>
              <![CDATA[url  /account/partner/people/v1/search?emails=test@flyin.com&partner=1]]>
            </line>
          </reporter-output>
        </test-method> <!-- partnercontroller_usersearch -->
      </class> <!-- accountsAPI.Account_Service_Partnercontroller_Usersearch -->
    </test> <!-- Account_Service_partnercontroller_Usersearch -->
    <test name="Account_Service_Partnercontroller_Updatetraveller" duration-ms="702" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
      <class name="accountsAPI.Account_Service_Partnercontroller_UpdateTraveller">
        <test-method status="SKIP" signature="partnercontroller_updatetraveller()[pri:0, instance:accountsAPI.Account_Service_Partnercontroller_UpdateTraveller@654f0d9c]" name="partnercontroller_updatetraveller" duration-ms="342" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Partnercontroller_UpdateTraveller.partnercontroller_updatetraveller(Account_Service_Partnercontroller_UpdateTraveller.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/partner/people/v1/traveller]]>
            </line>
            <line>
              <![CDATA[Response body partnercontroller_updatetraveller : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- partnercontroller_updatetraveller -->
        <test-method status="FAIL" signature="partnercontroller_updatetraveller()[pri:0, instance:accountsAPI.Account_Service_Partnercontroller_UpdateTraveller@654f0d9c]" name="partnercontroller_updatetraveller" duration-ms="328" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Partnercontroller_UpdateTraveller.partnercontroller_updatetraveller(Account_Service_Partnercontroller_UpdateTraveller.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/partner/people/v1/traveller]]>
            </line>
            <line>
              <![CDATA[Response body partnercontroller_updatetraveller : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- partnercontroller_updatetraveller -->
      </class> <!-- accountsAPI.Account_Service_Partnercontroller_UpdateTraveller -->
    </test> <!-- Account_Service_Partnercontroller_Updatetraveller -->
    <test name="Account_Service_peoplecontroller_GetuserByEmail" duration-ms="653" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
      <class name="accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail">
        <test-method status="SKIP" signature="peoplecontroller_getuserbyemail()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail@1139b2f3]" name="peoplecontroller_getuserbyemail" duration-ms="319" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail.peoplecontroller_getuserbyemail(Account_Service_Peoplecontroller_GetuserByEmail.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/people?docRequired=false&email=kirti.pandey@cleartrip.com&partner=1&travellersRequired=false&userPreference=false]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyemail : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyemail -->
        <test-method status="FAIL" signature="peoplecontroller_getuserbyemail()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail@1139b2f3]" name="peoplecontroller_getuserbyemail" duration-ms="301" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail.peoplecontroller_getuserbyemail(Account_Service_Peoplecontroller_GetuserByEmail.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/people?docRequired=false&email=kirti.pandey@cleartrip.com&partner=1&travellersRequired=false&userPreference=false]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyemail : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyemail -->
      </class> <!-- accountsAPI.Account_Service_Peoplecontroller_GetuserByEmail -->
    </test> <!-- Account_Service_peoplecontroller_GetuserByEmail -->
    <test name="Account_Service_Travellercontroller_UpdateTraveller" duration-ms="679" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
      <class name="accountsAPI.Account_Service_Travellercontroller_UpdateTraveller">
        <test-method status="SKIP" signature="travellercontroller_updatetraveller()[pri:0, instance:accountsAPI.Account_Service_Travellercontroller_UpdateTraveller@15c43bd9]" name="travellercontroller_updatetraveller" duration-ms="325" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Travellercontroller_UpdateTraveller.travellercontroller_updatetraveller(Account_Service_Travellercontroller_UpdateTraveller.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /people/traveller]]>
            </line>
            <line>
              <![CDATA[Response body travellercontroller_updatetraveller : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- travellercontroller_updatetraveller -->
        <test-method status="FAIL" signature="travellercontroller_updatetraveller()[pri:0, instance:accountsAPI.Account_Service_Travellercontroller_UpdateTraveller@15c43bd9]" name="travellercontroller_updatetraveller" duration-ms="301" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Travellercontroller_UpdateTraveller.travellercontroller_updatetraveller(Account_Service_Travellercontroller_UpdateTraveller.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /people/traveller]]>
            </line>
            <line>
              <![CDATA[Response body travellercontroller_updatetraveller : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- travellercontroller_updatetraveller -->
      </class> <!-- accountsAPI.Account_Service_Travellercontroller_UpdateTraveller -->
    </test> <!-- Account_Service_Travellercontroller_UpdateTraveller -->
    <test name="Account_Service_peoplecontroller_GetuserById" duration-ms="721" started-at="2020-05-04T05:15:15Z" finished-at="2020-05-04T05:15:16Z">
      <class name="accountsAPI.Account_Service_Peoplecontroller_GetuserById">
        <test-method status="SKIP" signature="peoplecontroller_getuserbyid()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserById@50b472aa]" name="peoplecontroller_getuserbyid" duration-ms="341" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserById.peoplecontroller_getuserbyid(Account_Service_Peoplecontroller_GetuserById.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  account/people/7707500017642?docRequired=false&partner=1&travellersRequired=false&userPreference=false]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyid : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyid -->
        <test-method status="FAIL" signature="peoplecontroller_getuserbyid()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserById@50b472aa]" name="peoplecontroller_getuserbyid" duration-ms="306" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserById.peoplecontroller_getuserbyid(Account_Service_Peoplecontroller_GetuserById.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  account/people/7707500017642?docRequired=false&partner=1&travellersRequired=false&userPreference=false]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyid : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyid -->
      </class> <!-- accountsAPI.Account_Service_Peoplecontroller_GetuserById -->
    </test> <!-- Account_Service_peoplecontroller_GetuserById -->
    <test name="Identity Service Add client" duration-ms="1365" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:17Z">
      <class name="accountsAPI.IdentityService_AddClient">
        <test-method status="PASS" signature="identityserviceaddclient()[pri:0, instance:accountsAPI.IdentityService_AddClient@3c407114]" name="identityserviceaddclient" duration-ms="1350" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:17Z">
          <reporter-output>
            <line>
              <![CDATA[url  /ctauth/client]]>
            </line>
            <line>
              <![CDATA[Response body identityserviceaddclient : {"id":"5eafa4e577438f00088fafa0","clientId":"likhithaabeO","clientSecret":"{DAax3ctffbhWZtvOfYFeiH1CFW1ngBbzSypaS6omAHc=}b6e8a21ff70da6ad86b6ffac12de596d3ee79e97","authenticated":true,"scope":"all","authorizedGrantTypes":"read,write,trust","redirectUri":["http://localhost:8080/ctauth/authorize"],"authorities":"authorities","session":true,"append":false}]]>
            </line>
            <line>
              <![CDATA[statusCode: 200]]>
            </line>
          </reporter-output>
        </test-method> <!-- identityserviceaddclient -->
      </class> <!-- accountsAPI.IdentityService_AddClient -->
    </test> <!-- Identity Service Add client -->
    <test name="Account_Service_Peoplecontroller_GetuserById_V2" duration-ms="1683" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:17Z">
      <class name="accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2">
        <test-method status="SKIP" signature="peoplecontroller_getuserbyid_v2()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2@1cbbffcd]" name="peoplecontroller_getuserbyid_v2" duration-ms="343" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2.peoplecontroller_getuserbyid_v2(Account_Service_Peoplecontroller_GetuserById_V2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/people/v2/41623980?docRequired=true&savedCards=true&travellersRequired=true&userPreference=true]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyid_v2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyid_v2 -->
        <test-method status="FAIL" signature="peoplecontroller_getuserbyid_v2()[pri:0, instance:accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2@1cbbffcd]" name="peoplecontroller_getuserbyid_v2" duration-ms="1304" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:17Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2.peoplecontroller_getuserbyid_v2(Account_Service_Peoplecontroller_GetuserById_V2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[url  /account/people/v2/41623980?docRequired=true&savedCards=true&travellersRequired=true&userPreference=true]]>
            </line>
            <line>
              <![CDATA[Response body peoplecontroller_getuserbyid_v2 : ]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- peoplecontroller_getuserbyid_v2 -->
      </class> <!-- accountsAPI.Account_Service_Peoplecontroller_GetuserById_V2 -->
    </test> <!-- Account_Service_Peoplecontroller_GetuserById_V2 -->
    <test name="Identity Service-Get resource" duration-ms="1826" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
      <class name="accountsAPI.IdentityService_Getresource">
        <test-method status="PASS" signature="identtiyservice_getresource()[pri:0, instance:accountsAPI.IdentityService_Getresource@7722c3c3]" name="identtiyservice_getresource" duration-ms="1793" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
          <reporter-output>
            <line>
              <![CDATA[Response body null : {"message":"Not authorized, Invalid token","traceId":"0af499968f397ea3"}]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- identtiyservice_getresource -->
      </class> <!-- accountsAPI.IdentityService_Getresource -->
    </test> <!-- Identity Service-Get resource -->
    <test name="Identity Service-Get Token Through refresh token" duration-ms="1760" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
      <class name="accountsAPI.Identtiyservice_get_tokenthroughrefreshToken">
        <test-method status="PASS" signature="identtiyservice_get_tokenthroughCode()[pri:0, instance:accountsAPI.Identtiyservice_get_tokenthroughrefreshToken@7714e963]" name="identtiyservice_get_tokenthroughCode" duration-ms="1739" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
          <reporter-output>
            <line>
              <![CDATA[Response body null : {"message":"Given Client id doesn't Exist","traceId":"dba4cad1a88dda65"}]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- identtiyservice_get_tokenthroughCode -->
      </class> <!-- accountsAPI.Identtiyservice_get_tokenthroughrefreshToken -->
    </test> <!-- Identity Service-Get Token Through refresh token -->
    <test name="Identity Service-Get Token Through Code" duration-ms="1772" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
      <class name="accountsAPI.Identtiyservice_get_tokenthroughCode">
        <test-method status="PASS" signature="identtiyservice_get_tokenthroughCode()[pri:0, instance:accountsAPI.Identtiyservice_get_tokenthroughCode@188715b5]" name="identtiyservice_get_tokenthroughCode" duration-ms="1763" started-at="2020-05-04T05:15:16Z" finished-at="2020-05-04T05:15:18Z">
          <reporter-output>
            <line>
              <![CDATA[Response body null : {"message":"Given Client id doesn't Exist","traceId":"69262e5d6e83b544"}]]>
            </line>
            <line>
              <![CDATA[statusCode: 401]]>
            </line>
          </reporter-output>
        </test-method> <!-- identtiyservice_get_tokenthroughCode -->
      </class> <!-- accountsAPI.Identtiyservice_get_tokenthroughCode -->
    </test> <!-- Identity Service-Get Token Through Code -->
  </suite> <!-- Accounts Service JAVA API - BB  -->
  <suite name="QA Services Scripts" duration-ms="0" started-at="2020-05-04T05:15:19Z" finished-at="2020-05-04T05:15:19Z">
    <groups>
    </groups>
  </suite> <!-- QA Services Scripts -->
</testng-results>
